### DISCUSSION TITLE
Having trouble mounting data.json through GitHub Actions (using mockoon-cli)

### DISCUSSION THREAD

**Discussion by hasanniz** [mockoon/mockoon#1243] [Help]
Hi, not sure where to ask this but I'm trying to run a Mockoon docker container in my server through GitHub Actions and having issues mounting the data.json file. 

This is my GitHub Actions workflow:
```
name: Run mock API server - Dev
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: show mocks/data.json file content
        run: cat mocks/data.json

      - name: ssh into server to deploy the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_KEY_DEV }}
          passphrase: ${{ secrets.SSH_PASSPHRASE_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            docker run \
              --name budget.mocks.dev -d \
              --network myNetwork \
              --restart always \
              --mount type=bind,source=./mocks/data.json,target=/data,readonly \
              -p 1033:3002 mockoon/cli:latest \
              -d data \
              -p 3002
```

The `cat mocks/data.json` correctly prints the entire file however when I try to mount the `mocks/data.json` file by doing `--mount type=bind,source=./mocks/data.json,target=/data,readonly` it gives me the error `docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/***/mocks/data.json.`.

Any help will be appreciated, thanks.

---

Folder Structure:
![Screenshot 2023-12-30 at 3 20 57 pm](https://github.com/mockoon/mockoon/assets/8472738/fbd25849-c8a0-4431-9121-b03229b7759a)

---

Error:
![Screenshot 2023-12-30 at 3 17 10 pm](https://github.com/mockoon/mockoon/assets/8472738/18662c9c-6869-4393-897f-6f05bc355a19)
