### DISCUSSION TITLE
Is there a Docker server version of Mockoon?

### DISCUSSION THREAD

**Discussion by PureKrome** [mockoon/mockoon#1410] [General]
👋🏻 G'Day folks!

I'm trying to understand if there's a docker image of the "desktop" product available? Basically, could we run Mockoon locally as a docker instance and then have our code (whatever language) make HTTP calls to a specific localhost endpoint and based on some config, have specific responses, returned. No need to leave the localhost machine.

I can see there's a CLI docker version, but i'm _assuming_ that's just to use the docker instance to connect to a remote cloud mockoon instance?

**Comment by 255kb** [comment]
Hi, there is no such thing as running the desktop app in Docker (you could probably do it, but we don't provide an image for that). 

The CLI is what you are looking for. The usual workflow is the following: 

- you design your mock in the desktop app, it saves everything in a JSON data file. You can also run the mock in the desktop app.
- you install the CLI somewhere (local machine, server, CI, etc.) and you [run it with a data file](https://github.com/mockoon/mockoon/tree/main/packages/cli#run-a-mock-api-with-the-cli). 

The CLI will run the mock in the exact same way as the desktop app, but headless. 
If it's a matter of sharing your setup, you can move the data file in a git tracked folder and use it from there with the desktop app or CLI. 

[CLI tutorial](https://mockoon.com/tutorials/run-mock-api-anywhere-cli/)

**Reply by PureKrome** [reply]
Yep - i think this is working 💪🏻 

for future-me, here's a docker-compose.yml snippet

```
  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon
    ports:
      - "3000:3000"
    volumes:
      - ./your-data.json:/data/pewpew.json:ro
    command: ["-d", "/data/pewpew.json", "-p", "3000"]
```
