### DISCUSSION TITLE
Does anyone have an example project using the Mockoon Serverless package?

### DISCUSSION THREAD

**Discussion by deanmalan** [mockoon/mockoon#927] [Help]
I've been trying to use the [Mockoon Serverless package](https://github.com/mockoon/mockoon/tree/main/packages/serverless) today, but NodeJS is not my strong point. I've tried to use both the Serverless framework and AWS SAM, but haven't been able to successfully mock requests.

Does anyone perhaps have a template AWS SAM or Serverless framework project I could try?

**Comment by 255kb** [comment]
This package is still very new and a bit rough. The code in the repository should be enough to run your mock in an AWS Lambda function of GCP Function. However, you may have to have some setup to redirect all the trafic to the function. 
If you use the Serverless framework, you may have to use this kind of config (in serverless.yml): 

```yaml
functions:
  mock-api:
    image:
      name: mockoon-serverless
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
```

I never used the Serverless framework, so I'm just repeating what I have been told by users running Mockoon in lambda functions. And I didn't have time to test myself. 
And if you find something that is missing in the documentation feel free to open a PR so we improve the package 😀
