### DISCUSSION TITLE
Not all environments getting started through the CLI

### DISCUSSION THREAD

**Discussion by Marvin-S** [mockoon/mockoon#955] [Help] [answered]
**Describe the bug**

I want to run the Mockoon CLI via Docker Compose and have three environments that should be executed at startup, but only two of them are getting started. To be more precise only the first two (even if I switch their order in the start command).
All those environments are simple with just one dummy endpoint.
It is also strange that although the first two environments are running, `mockoon-cli list` says, that no processes are runnning.

**To Reproduce**

This is my docker compose file:
```yaml
version: "3.8"

services:
  mockoon-cli:
    image: mockoon/cli:2.3.0
    container_name: mockoon
    command: mockoon-cli start --data /data/Env1.json /data/Env2.json /data/Env3.json
    ports:
      - "127.0.0.1:52525:52525"
      - "127.0.0.1:52526:52526"
      - "127.0.0.1:52527:52527"
    restart: unless-stopped
    volumes:
      - ./Configs/:/data
```

Attached you will find a zip archive containing all the files to reproduce (environment and docker compose files).
Just open the folder, run the following command: `docker compose up -d` and take a look at the container logs. They should look like this:
```json
{"level":"info","message":"Server started on port 52525","mockName":"mockoon-env1","timestamp":"2023-02-22T11:12:43.310Z"}
{"level":"info","message":"Server started on port 52526","mockName":"mockoon-env2","timestamp":"2023-02-22T11:12:43.316Z"}
```

**Mockoon version:**

I'm using the image mockoon/cli:2.3.0

**What I've tried**
- Changing the order of the environments -> Still only the first two envs are executed
- Manually running `mockoon-cli start` inside the container with just the third environment -> Starts the third environment
- Running each environment in its own container -> Runs as expected

**Attachments**
[MockoonCLIWith3Envs.zip](https://github.com/mockoon/mockoon/files/10803083/MockoonCLIWith3Envs.zip)

**Comment by 255kb** [comment, marked as answer]
Running the 3 envs was ok with the CLI or a `docker run` command like in the documentation. But somehow it was failing also for me with your setup. 
I found the issue after a certain amount of debugging. 
Our published Docker image has an `ENTRYPOINT` that you didn't override. Your Docker compose `command` was concatenated with the `ENTRYPOINT`, and Node.js was trying to resolve a hostname named "start" ("mockoon-cli" was ignored): 

```
'Args': ['start',
          '--hostname',
          '0.0.0.0',
          '--daemon-off',
          'mockoon-cli',
          'start',
          '--data',
          '/data/Env1.json',
          '/data/Env2.json',
          '/data/Env3.json',
...
```

You can solve this by using `entrypoint` instead or reduce the size of the `command` by passing only the data:

```yaml
version: "3.8"

services:
  mockoon-cli:
    image: mockoon/cli:2.3.0
    container_name: mockoon
    # entrypoint: mockoon-cli start --daemon-off --data /data/Env1.json /data/Env2.json /data/Env3.json
    command: --data /data/Env1.json /data/Env2.json /data/Env3.json
    ports:
      - "127.0.0.1:52525:52525"
      - "127.0.0.1:52526:52526"
      - "127.0.0.1:52527:52527"
    restart: unless-stopped
    volumes:
      - ./Configs/:/data
```

I was wondering since the beginning how your CLI could run with `daemon-off` even if you didn't provided the flag. Now I know! 🙂

I will try to improve error reporting in the future.
